user: { { UserName } }
password: { { Password } }
masters:
  - { { Master1 ip } }
  - { { Master2 ip } }
  - { { ... } }
workers:
  - { { Worker1 ip } }
  - { { Worker2 ip } }
  - { { ... } }
k8s_version: v1.21.0 # used to kubeadm version option
pod_network_cidr: 10.244.0.0/16 # current cni setting is Flannel
control_plane_endpoint: { { LB or Proxy Server IP } }